### ISSUE TITLE
Rename the repo 

### ISSUE THREAD

**Issue by johny-b** [golemfactory/dapp-store#4]
E.g. `dapp-examples`, `dapp-gallery`, `dapp-hub` or something like this.

Reason: there is a concept of `dapp-store` that is much wider than a repo with desciptors.

Details: @stranger80 .

**Comment by stranger80** [comment]
After some thought, I vote for `dapp-examples`

**Comment by VanDavv** [comment]
There is a separate repository for the source code of the dapps - https://github.com/golemfactory/dapp-experiments
The dapp-store serves now as a descriptor-gathering place, without source codes
